title: Andrew Leatt-Hayter
email: aleatthayter@gmail.com
description: >-
  Building AI agents for the mining and energy sectors.
baseurl: ""
url: "https://aleatthayter.github.io"
github_username: aleatthayter

# Build settings
timezone: Australia/Sydney
theme: minima

plugins:
  - jekyll-feed